// Generated by gencpp from file vision_perception/RectArray.msg
// DO NOT EDIT!


#ifndef VISION_PERCEPTION_MESSAGE_RECTARRAY_H
#define VISION_PERCEPTION_MESSAGE_RECTARRAY_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace vision_perception
{
template <class ContainerAllocator>
struct RectArray_
{
  typedef RectArray_<ContainerAllocator> Type;

  RectArray_()
    : x()
    , y()
    , width()
    , height()  {
    }
  RectArray_(const ContainerAllocator& _alloc)
    : x(_alloc)
    , y(_alloc)
    , width(_alloc)
    , height(_alloc)  {
  (void)_alloc;
    }



   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _x_type;
  _x_type x;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _y_type;
  _y_type y;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _width_type;
  _width_type width;

   typedef std::vector<int32_t, typename ContainerAllocator::template rebind<int32_t>::other >  _height_type;
  _height_type height;




  typedef boost::shared_ptr< ::vision_perception::RectArray_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::vision_perception::RectArray_<ContainerAllocator> const> ConstPtr;

}; // struct RectArray_

typedef ::vision_perception::RectArray_<std::allocator<void> > RectArray;

typedef boost::shared_ptr< ::vision_perception::RectArray > RectArrayPtr;
typedef boost::shared_ptr< ::vision_perception::RectArray const> RectArrayConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::vision_perception::RectArray_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::vision_perception::RectArray_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace vision_perception

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': False, 'IsMessage': True, 'HasHeader': False}
// {'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'vision_perception': ['/home/xd/catkin_ws/src/vision_perception/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::vision_perception::RectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::vision_perception::RectArray_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_perception::RectArray_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::vision_perception::RectArray_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_perception::RectArray_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::vision_perception::RectArray_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::vision_perception::RectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "bde2ed7e7fbae64eb6bd2a19f9089384";
  }

  static const char* value(const ::vision_perception::RectArray_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xbde2ed7e7fbae64eULL;
  static const uint64_t static_value2 = 0xb6bd2a19f9089384ULL;
};

template<class ContainerAllocator>
struct DataType< ::vision_perception::RectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "vision_perception/RectArray";
  }

  static const char* value(const ::vision_perception::RectArray_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::vision_perception::RectArray_<ContainerAllocator> >
{
  static const char* value()
  {
    return "int32[] x\n\
int32[] y\n\
int32[] width\n\
int32[] height\n\
";
  }

  static const char* value(const ::vision_perception::RectArray_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::vision_perception::RectArray_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.x);
      stream.next(m.y);
      stream.next(m.width);
      stream.next(m.height);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct RectArray_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::vision_perception::RectArray_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::vision_perception::RectArray_<ContainerAllocator>& v)
  {
    s << indent << "x[]" << std::endl;
    for (size_t i = 0; i < v.x.size(); ++i)
    {
      s << indent << "  x[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.x[i]);
    }
    s << indent << "y[]" << std::endl;
    for (size_t i = 0; i < v.y.size(); ++i)
    {
      s << indent << "  y[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.y[i]);
    }
    s << indent << "width[]" << std::endl;
    for (size_t i = 0; i < v.width.size(); ++i)
    {
      s << indent << "  width[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.width[i]);
    }
    s << indent << "height[]" << std::endl;
    for (size_t i = 0; i < v.height.size(); ++i)
    {
      s << indent << "  height[" << i << "]: ";
      Printer<int32_t>::stream(s, indent + "  ", v.height[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // VISION_PERCEPTION_MESSAGE_RECTARRAY_H
